run:
  skip-files:
    - scripts/migrateLinks.go
    - scripts/mkdata.go
    - scripts/migrateUsers.go
    - database/database_test.go
    - database/helpers_test.go

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - unconvert
